### ISSUE TITLE
Cannot scope address parameters

### ISSUE THREAD

**Issue by jfschwarz** [gnosis/zodiac-modifier-roles#175]
When trying to define a required value for an address parameter it errors with:

```
Error: invalid address (argument="address", value=["0x325b8aB1BD08FbA28332796e6e4e979Fc3776BA9"], code=INVALID_ARGUMENT, version=address/5.5.0) (argument="_to", value=["0x325b8aB1BD08FbA28332796e6e4e979Fc3776BA9"], code=INVALID_ARGUMENT, version=abi/5.5.0)
    at e.value (index.ts:225:28)
    at e.value (index.ts:237:20)
    at e.value (index.ts:241:21)
    at n.value (abstract-coder.ts:68:16)
    at n.value (address.ts:22:18)
    at array.ts:71:19
    at Array.forEach (<anonymous>)
    at v (array.ts:54:12)
    at n.value (tuple.ts:54:16)
    at e.value (abi-coder.ts:112:15)
```

First reported here: https://discord.com/channels/881881751369175040/884777203332710460/1070415678361841694

**Comment by jfschwarz** [comment]
this is fixed in latest main
